"""Single source of truth for product metadata."""
APP_NAME = "DataSense"
APP_VERSION = "2.2.1"
APP_TAGLINE = "Trusted data analysis, modelling and visualisation for Windows"
APP_PUBLISHER = "Ali Marandi"
APP_URL = "https://github.com/Ali-Marandi/DataSense"
