apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datasense-control-plane
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - control-plane.yaml
  - outbox-worker.yaml
  - network-policy.yaml
  - pdb.yaml
  - hpa.yaml
  - servicemonitor.yaml
commonLabels:
  app.kubernetes.io/part-of: datasense
  app.kubernetes.io/component: enterprise-control-plane
