from PyQt6.QtWidgets import (QWidget, QVBoxLayout, QPushButton, QLabel, 
                             QFileDialog, QMessageBox, QHBoxLayout)
from core.report_generator import ReportGenerator
import os

class ReportTab(QWidget):
    def __init__(self, data_manager):
        super().__init__()
        self.data_manager = data_manager
        self.report_gen = ReportGenerator(data_manager)
        self.init_ui()

    def init_ui(self):
        self.layout = QVBoxLayout(self)
        
        self.layout.addWidget(QLabel("Report Generation & Export:"))
        
        self.info_label = QLabel("Generate a professional PDF report including statistical summaries.")
        self.info_label.setWordWrap(True)
        self.layout.addWidget(self.info_label)

        self.btn_pdf = QPushButton("Export Analysis to PDF Report")
        self.btn_pdf.setMinimumHeight(50)
        self.btn_pdf.setStyleSheet("background-color: #2E8B57; color: white; font-weight: bold;")
        self.btn_pdf.clicked.connect(self.export_pdf)
        self.layout.addWidget(self.btn_pdf)

        self.btn_html = QPushButton("Export Interactive HTML Dashboard")
        self.btn_html.setMinimumHeight(50)
        self.btn_html.setStyleSheet("background-color: #4682B4; color: white; font-weight: bold;")
        self.btn_html.clicked.connect(self.export_interactive_html)
        self.layout.addWidget(self.btn_html)

        self.layout.addStretch()

    def export_pdf(self):
        if self.data_manager.df is None:
            QMessageBox.warning(self, "Warning", "No data available to report.")
            return

        file_path, _ = QFileDialog.getSaveFileName(self, "Save PDF Report", "DataSense_Report.pdf", "PDF Files (*.pdf)")
        
        if file_path:
            success, message = self.report_gen.generate_pdf(file_path)
            if success:
                QMessageBox.information(self, "Success", "PDF Report saved successfully!")
            else:
                QMessageBox.critical(self, "Error", f"Failed to generate report: {message}")

    def export_interactive_html(self):
        """صادرات داشبورد تعاملی HTML"""
        if self.data_manager.df is None:
            QMessageBox.warning(self, "Warning", "No data available.")
            return

        file_path, _ = QFileDialog.getSaveFileName(self, "Save Interactive Dashboard", "Dashboard.html", "HTML Files (*.html)")
        if file_path:
            from core.report import ReportBuilder
            import plotly.express as px
            
            report = ReportBuilder(title="Interactive DataSense Dashboard", subtitle="Generated by DataSense AI")
            report.add_metrics("Dataset Overview", {
                "Rows": len(self.data_manager.df),
                "Columns": len(self.data_manager.df.columns)
            })
            
            # Add an interactive chart
            numeric_cols = self.data_manager.df.select_dtypes(include=['number']).columns
            if len(numeric_cols) >= 2:
                fig = px.scatter(self.data_manager.df, x=numeric_cols[0], y=numeric_cols[1], title="Interactive Scatter Plot")
                report.add_plotly_figure("Scatter Analysis", fig)
            
            report.save(file_path)
            QMessageBox.information(self, "Success", "Interactive Dashboard saved successfully!")
